name: goreleaser

on:
    push:
      branches:
        - "main"

env:
    HOMEBREW_TAP: "homebrew-cli-tap"
    OWNER_EMAIL: "dev@kaytu.io"

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          tag_prefix: v
  goreleaser:
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          REPOSITORY_NAME: ${{ github.repository }}
          REPOSITORY_OWNER: ${{ github.repository_owner }}
          HOMEBREW_TAP: ${{ env.HOMEBREW_TAP }}
          OWNER_EMAIL: ${{ env.OWNER_EMAIL }}